/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv-entry".
 */
export interface CvEntry {
  id: string;
  location: string;
  date: string;
  title: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  roles: ('admin' | 'public')[];
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  'name-long': string;
  description: string;
  github: string;
  marketing?: string;
  dedicated?: boolean;
  priority?: number;
  layout: (
    | {
        title: string;
        interactions: {
          user: string;
          cmd: string;
          body: string;
          link?: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'console-layout';
      }
    | {
        title: string;
        body: string;
        store: string;
        source: string;
        id?: string;
        blockName?: string;
        blockType: 'card-layout';
      }
    | {
        title: string;
        tech: string;
        operator: string;
        result: string;
        source: string;
        id?: string;
        blockName?: string;
        blockType: 'browser-layout';
      }
    | {
        title: string;
        nodes: {
          content?: string;
          icon?: string;
          link?: string;
          'low-priority'?: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cluster-layout';
      }
  )[];
  createdAt: string;
  updatedAt: string;
}
